//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_cliente> tb_cliente { get; set; }
        public DbSet<tb_cliente_aula> tb_cliente_aula { get; set; }
        public DbSet<tb_compra> tb_compra { get; set; }
        public DbSet<tb_conta> tb_conta { get; set; }
        public DbSet<tb_folha_pagamento> tb_folha_pagamento { get; set; }
        public DbSet<tb_fornecedor> tb_fornecedor { get; set; }
        public DbSet<tb_funcionario> tb_funcionario { get; set; }
        public DbSet<tb_login> tb_login { get; set; }
        public DbSet<tb_plano> tb_plano { get; set; }
        public DbSet<tb_produto> tb_produto { get; set; }
        public DbSet<tb_tipo_conta> tb_tipo_conta { get; set; }
        public DbSet<tb_venda_plano> tb_venda_plano { get; set; }
        public DbSet<tb_venda_produto> tb_venda_produto { get; set; }
    }
}
