//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_colaborador
    {
        public int id_colaborador { get; set; }
        public string nm_colaborador { get; set; }
        public System.DateTime nascimento { get; set; }
        public System.DateTime contratacao { get; set; }
        public System.DateTime demicao { get; set; }
        public string endereco { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
    }
}
