//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        public tb_cliente()
        {
            this.tb_cliente_aula = new HashSet<tb_cliente_aula>();
            this.tb_venda_plano = new HashSet<tb_venda_plano>();
            this.tb_venda_produto = new HashSet<tb_venda_produto>();
        }
    
        public int id_cliente { get; set; }
        public string nm_cliente { get; set; }
        public int idade { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public string cep { get; set; }
        public string observacao { get; set; }
        public string estado { get; set; }
        public string bairro { get; set; }
        public string periodo { get; set; }
        public string nm_responsavel { get; set; }
    
        public virtual ICollection<tb_cliente_aula> tb_cliente_aula { get; set; }
        public virtual ICollection<tb_venda_plano> tb_venda_plano { get; set; }
        public virtual ICollection<tb_venda_produto> tb_venda_produto { get; set; }
    }
}
