//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedor
    {
        public tb_fornecedor()
        {
            this.tb_produto_compra = new HashSet<tb_produto_compra>();
        }
    
        public int id_fornecedor { get; set; }
        public string nm_fornecedor { get; set; }
        public string nm_responsavel { get; set; }
        public string cnpj { get; set; }
        public string tell_contato { get; set; }
        public string tell_contato2 { get; set; }
    
        public virtual ICollection<tb_produto_compra> tb_produto_compra { get; set; }
    }
}
