//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedor
    {
        public tb_fornecedor()
        {
            this.tb_compra = new HashSet<tb_compra>();
            this.tb_produto = new HashSet<tb_produto>();
        }
    
        public int id_fornecedor { get; set; }
        public string nm_fornecedor { get; set; }
        public string nm_responsavel { get; set; }
        public string cnpj { get; set; }
        public string tell_contato { get; set; }
        public string tell_contato2 { get; set; }
    
        public virtual ICollection<tb_compra> tb_compra { get; set; }
        public virtual ICollection<tb_produto> tb_produto { get; set; }
    }
}
