//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        public tb_funcionario()
        {
            this.tb_cliente_aula = new HashSet<tb_cliente_aula>();
            this.tb_folha_pagamento = new HashSet<tb_folha_pagamento>();
        }
    
        public int id_funcionario { get; set; }
        public string nm_funcionario { get; set; }
        public System.DateTime nascimento { get; set; }
        public System.DateTime contratacao { get; set; }
        public System.DateTime demicao { get; set; }
        public decimal vl_salario { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public bool genero { get; set; }
        public System.TimeSpan hr_entrada { get; set; }
        public System.TimeSpan hr_almoco { get; set; }
        public System.TimeSpan hr_saida { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public string cep { get; set; }
        public int id_login { get; set; }
        public string cargo { get; set; }
        public string rua { get; set; }
        public string estado { get; set; }
        public string bairro { get; set; }
    
        public virtual ICollection<tb_cliente_aula> tb_cliente_aula { get; set; }
        public virtual ICollection<tb_folha_pagamento> tb_folha_pagamento { get; set; }
        public virtual tb_login tb_login { get; set; }
    }
}
