//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_login
    {
        public tb_login()
        {
            this.tb_funcionario = new HashSet<tb_funcionario>();
        }
    
        public int id_login { get; set; }
        public string nm_usuario { get; set; }
        public string sen_usuario { get; set; }
        public System.DateTime login { get; set; }
    
        public virtual ICollection<tb_funcionario> tb_funcionario { get; set; }
    }
}
