//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_compra_item
    {
        public int id_pedido_compra_item { get; set; }
        public int id_pedido_compra { get; set; }
        public int id_produto { get; set; }
    
        public virtual tb_pedido_compra tb_pedido_compra { get; set; }
        public virtual tb_produto_compra tb_produto_compra { get; set; }
    }
}
