//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_compra
    {
        public tb_pedido_compra()
        {
            this.tb_pedido_compra_item = new HashSet<tb_pedido_compra_item>();
        }
    
        public int id_pedido_compra { get; set; }
        public System.DateTime dt_pedido { get; set; }
    
        public virtual ICollection<tb_pedido_compra_item> tb_pedido_compra_item { get; set; }
    }
}
