//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto
    {
        public tb_produto()
        {
            this.tb_venda_produto = new HashSet<tb_venda_produto>();
        }
    
        public int id_produto { get; set; }
        public string nm_produto { get; set; }
        public decimal preco { get; set; }
        public int quantidade { get; set; }
        public int id_fornecedor { get; set; }
    
        public virtual tb_fornecedor tb_fornecedor { get; set; }
        public virtual ICollection<tb_venda_produto> tb_venda_produto { get; set; }
    }
}
