//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_conta
    {
        public tb_tipo_conta()
        {
            this.tb_conta = new HashSet<tb_conta>();
        }
    
        public int id_tipo_conta { get; set; }
        public string conta { get; set; }
    
        public virtual ICollection<tb_conta> tb_conta { get; set; }
    }
}
