//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venda_produto
    {
        public int id_venda_produto { get; set; }
        public string nm_produto { get; set; }
        public decimal vl_produto { get; set; }
        public int qtd_produto { get; set; }
        public int id_produto { get; set; }
        public int id_cliente { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_produto tb_produto { get; set; }
    }
}
