
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cultura_Musical.Database.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class fluxo_de_caixa
{

    public System.DateTime data_pagamento { get; set; }

    public Nullable<decimal> valor_pago { get; set; }

    public string tipo_operação { get; set; }

}

}
