//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_agenda_estudio
    {
        public int id_agenda_estudio { get; set; }
        public System.TimeSpan hr_entrada { get; set; }
        public System.TimeSpan hr_saida { get; set; }
        public int qtd_pessoa { get; set; }
        public System.DateTime dt_estudio { get; set; }
        public int id_cliente { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
    }
}
