
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cultura_Musical.Database.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_agenda_all
{

    public int id_agenda_all { get; set; }

    public Nullable<System.DateTime> dt_dia { get; set; }

    public Nullable<System.DateTime> dt_semana { get; set; }

    public Nullable<System.DateTime> dt_mes { get; set; }

    public Nullable<System.DateTime> dt_ano { get; set; }

    public int id_compromisso { get; set; }



    public virtual tb_compromisso tb_compromisso { get; set; }

}

}
