//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_beneficio
    {
        public tb_beneficio()
        {
            this.tb_funcionario = new HashSet<tb_funcionario>();
        }
    
        public int id_beneficio { get; set; }
        public decimal ds_vt { get; set; }
        public decimal ds_va { get; set; }
        public decimal ds_vr { get; set; }
        public decimal ds_convenio { get; set; }
    
        public virtual ICollection<tb_funcionario> tb_funcionario { get; set; }
    }
}
