
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cultura_Musical.Database.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_beneficio
{

    public tb_beneficio()
    {

        this.tb_folha_pagamento = new HashSet<tb_folha_pagamento>();

    }


    public int id_beneficio { get; set; }

    public decimal vt { get; set; }

    public decimal va { get; set; }

    public decimal vr { get; set; }

    public decimal convenio { get; set; }

    public int id_funcionario { get; set; }



    public virtual ICollection<tb_folha_pagamento> tb_folha_pagamento { get; set; }

    public virtual tb_funcionario tb_funcionario { get; set; }

}

}
