//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_beneficio
    {
        public tb_beneficio()
        {
            this.tb_folha_pagamento = new HashSet<tb_folha_pagamento>();
        }
    
        public int id_beneficio { get; set; }
        public decimal vt { get; set; }
        public decimal va { get; set; }
        public decimal vr { get; set; }
        public decimal convenio { get; set; }
        public int id_funcionario { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
        public virtual ICollection<tb_folha_pagamento> tb_folha_pagamento { get; set; }
    }
}
