
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cultura_Musical.Database.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_compra
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_compra()
    {

        this.tb_produto = new HashSet<tb_produto>();

    }


    public int id_compra { get; set; }

    public System.DateTime dt_entrega { get; set; }

    public System.DateTime dt_compra { get; set; }

    public decimal vl_pagar { get; set; }

    public int id_fornecedor { get; set; }



    public virtual tb_fornecedor tb_fornecedor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_produto> tb_produto { get; set; }

}

}
