//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compra
    {
        public tb_compra()
        {
            this.tb_compra_item = new HashSet<tb_compra_item>();
            this.tb_estoque = new HashSet<tb_estoque>();
        }
    
        public int id_compra { get; set; }
        public System.DateTime dt_compra { get; set; }
        public int qtd_produto { get; set; }
        public decimal vl_compra { get; set; }
        public int tb_fornecedor_id_fornecedor { get; set; }
    
        public virtual ICollection<tb_compra_item> tb_compra_item { get; set; }
        public virtual tb_fornecedor tb_fornecedor { get; set; }
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
    }
}
