//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compra_item
    {
        public int id_compra_item { get; set; }
        public int tb_compra_id_compra { get; set; }
        public int tb_produto_compra_id_produto_compra { get; set; }
    
        public virtual tb_compra tb_compra { get; set; }
        public virtual tb_produto_compra tb_produto_compra { get; set; }
    }
}
