//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        public tb_cliente()
        {
            this.tb_agenda_estudio = new HashSet<tb_agenda_estudio>();
            this.tb_aula = new HashSet<tb_aula>();
            this.tb_venda_plano = new HashSet<tb_venda_plano>();
        }
    
        public int id_cliente { get; set; }
        public string nm_cliente { get; set; }
        public int ds_idade { get; set; }
        public string ds_telefone { get; set; }
        public string ds_email { get; set; }
        public string ds_rg { get; set; }
        public string ds_cpf { get; set; }
        public string ds_cep { get; set; }
        public string ds_observacao { get; set; }
        public string ds_estado { get; set; }
        public string ds_bairro { get; set; }
        public string ds_periodo { get; set; }
        public string nm_responsavel { get; set; }
        public string ds_nivel { get; set; }
    
        public virtual ICollection<tb_agenda_estudio> tb_agenda_estudio { get; set; }
        public virtual ICollection<tb_aula> tb_aula { get; set; }
        public virtual ICollection<tb_venda_plano> tb_venda_plano { get; set; }
    }
}
