
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cultura_Musical.Database.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_compromisso
{

    public int id_compromisso { get; set; }

    public System.DateTime dt_dia { get; set; }

    public System.TimeSpan hr_inicio { get; set; }

    public System.TimeSpan hr_final { get; set; }

    public int id_cliente { get; set; }

    public int sala { get; set; }

}

}
