
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cultura_Musical.Database.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_compra
{

    public tb_compra()
    {

        this.tb_compra_item = new HashSet<tb_compra_item>();

    }


    public int id_compra { get; set; }

    public System.DateTime dt_entrega { get; set; }

    public System.DateTime dt_compra { get; set; }

    public decimal vl_pagar { get; set; }

    public int id_fornecedor { get; set; }



    public virtual ICollection<tb_compra_item> tb_compra_item { get; set; }

    public virtual tb_fornecedor tb_fornecedor { get; set; }

}

}
