//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_conta
    {
        public int id_conta { get; set; }
        public decimal vl_pagar { get; set; }
        public int id_tipo_conta { get; set; }
        public System.DateTime dt_conta { get; set; }
        public System.DateTime dt_pagamento { get; set; }
    
        public virtual tb_tipo_conta tb_tipo_conta { get; set; }
    }
}
