//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_conta
    {
        public int id_conta { get; set; }
        public decimal vl_pagar { get; set; }
        public int id_tipo_conta { get; set; }
        public System.DateTime dt_conta { get; set; }
        public System.DateTime dt_pagamento { get; set; }
    
        public virtual tb_tipo_conta tb_tipo_conta { get; set; }
    }
}
