//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_dia_semana
    {
        public tb_dia_semana()
        {
            this.tb_escala = new HashSet<tb_escala>();
        }
    
        public int id_dia_semana { get; set; }
        public bool d_segunda { get; set; }
        public bool d_terca { get; set; }
        public bool d_quarta { get; set; }
        public bool d_quinta { get; set; }
        public bool d_sexta { get; set; }
        public bool d_sabado { get; set; }
        public bool d_domingo { get; set; }
    
        public virtual ICollection<tb_escala> tb_escala { get; set; }
    }
}
