//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_escala
    {
        public int id_escala { get; set; }
        public int id_dia_semana { get; set; }
        public int id_horario { get; set; }
        public int cod_escala { get; set; }
    
        public virtual tb_dia_semana tb_dia_semana { get; set; }
        public virtual tb_horario tb_horario { get; set; }
    }
}
