//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_escala
    {
        public int id_escala { get; set; }
        public int id_dia_semana { get; set; }
        public int id_horario { get; set; }
        public int cod_escala { get; set; }
    
        public virtual tb_dia_semana tb_dia_semana { get; set; }
        public virtual tb_horario tb_horario { get; set; }
    }
}
