//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_estoque
    {
        public int id_estoque { get; set; }
        public string qtd_estoque { get; set; }
        public int id_produto { get; set; }
    
        public virtual tb_produto tb_produto { get; set; }
    }
}
