//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_escala_funcionario
    {
        public int id_escala_funcionario { get; set; }
        public System.DateTime dt_inicio { get; set; }
        public System.DateTime dt_final { get; set; }
        public int id_funcionario { get; set; }
        public int cod_escala { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
