//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_financeiro
    {
        public tb_financeiro()
        {
            this.tb_folha_pagamento = new HashSet<tb_folha_pagamento>();
            this.tb_funcionario = new HashSet<tb_funcionario>();
        }
    
        public int id_financeiro { get; set; }
        public decimal ds_fgts { get; set; }
        public decimal ds_inss { get; set; }
        public decimal ds_irrf { get; set; }
    
        public virtual ICollection<tb_folha_pagamento> tb_folha_pagamento { get; set; }
        public virtual ICollection<tb_funcionario> tb_funcionario { get; set; }
    }
}
