//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedor
    {
        public tb_fornecedor()
        {
            this.tb_compra = new HashSet<tb_compra>();
        }
    
        public int id_fornecedor { get; set; }
        public string nm_fornecedor { get; set; }
        public string tell_contato { get; set; }
        public string tell_contato2 { get; set; }
        public string rua { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public string ds_cnpj { get; set; }
        public string ds_email { get; set; }
        public string inscicao_estadual { get; set; }
    
        public virtual ICollection<tb_compra> tb_compra { get; set; }
    }
}
