//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        public tb_funcionario()
        {
            this.tb_beneficio = new HashSet<tb_beneficio>();
            this.tb_cliente_aula = new HashSet<tb_cliente_aula>();
            this.tb_folha_pagamento = new HashSet<tb_folha_pagamento>();
            this.tb_holerite = new HashSet<tb_holerite>();
            this.tb_jornada = new HashSet<tb_jornada>();
            this.tb_login = new HashSet<tb_login>();
        }
    
        public int id_funcionario { get; set; }
        public string nm_funcionario { get; set; }
        public System.DateTime dt_nascimento { get; set; }
        public System.DateTime dt_contratacao { get; set; }
        public Nullable<System.DateTime> dt_demicao { get; set; }
        public decimal vl_salario { get; set; }
        public string ds_telefone { get; set; }
        public string ds_email { get; set; }
        public bool ds_genero { get; set; }
        public string ds_rg { get; set; }
        public string ds_cpf { get; set; }
        public string ds_cep { get; set; }
        public string ds_cargo { get; set; }
        public string ds_rua { get; set; }
        public string ds_estado { get; set; }
        public string ds_bairro { get; set; }
        public bool ds_prolabore { get; set; }
        public Nullable<decimal> vl_13_salario { get; set; }
    
        public virtual ICollection<tb_beneficio> tb_beneficio { get; set; }
        public virtual ICollection<tb_cliente_aula> tb_cliente_aula { get; set; }
        public virtual ICollection<tb_folha_pagamento> tb_folha_pagamento { get; set; }
        public virtual ICollection<tb_holerite> tb_holerite { get; set; }
        public virtual ICollection<tb_jornada> tb_jornada { get; set; }
        public virtual ICollection<tb_login> tb_login { get; set; }
    }
}
