//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_funcionario()
        {
            this.tb_aula = new HashSet<tb_aula>();
            this.tb_folha_pagamento = new HashSet<tb_folha_pagamento>();
            this.tb_login = new HashSet<tb_login>();
            this.tb_jornada = new HashSet<tb_jornada>();
            this.tb_ponto = new HashSet<tb_ponto>();
        }
    
        public int id_funcionario { get; set; }
        public string nm_funcionario { get; set; }
        public System.DateTime dt_nascimento { get; set; }
        public System.DateTime dt_contratacao { get; set; }
        public Nullable<System.DateTime> dt_demicao { get; set; }
        public decimal vl_salario { get; set; }
        public string ds_telefone { get; set; }
        public string ds_email { get; set; }
        public string ds_genero { get; set; }
        public string ds_rg { get; set; }
        public string ds_cpf { get; set; }
        public string ds_cep { get; set; }
        public string ds_cargo { get; set; }
        public string ds_rua { get; set; }
        public string ds_estado { get; set; }
        public string ds_bairro { get; set; }
        public string ds_complemento { get; set; }
        public int id_beneficio { get; set; }
        public string ds_cidade { get; set; }
        public byte[] ft_funcionario { get; set; }
        public int nmr_funcionario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_aula> tb_aula { get; set; }
        public virtual tb_beneficio tb_beneficio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_folha_pagamento> tb_folha_pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_login> tb_login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_jornada> tb_jornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ponto> tb_ponto { get; set; }
    }
}
