//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_horario
    {
        public tb_horario()
        {
            this.tb_escala = new HashSet<tb_escala>();
        }
    
        public int id_horario { get; set; }
        public System.TimeSpan hr_entrada { get; set; }
        public System.TimeSpan hr_almoco { get; set; }
        public System.TimeSpan hr_retorno { get; set; }
        public System.TimeSpan hr_saida { get; set; }
    
        public virtual ICollection<tb_escala> tb_escala { get; set; }
    }
}
