//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_jornada
    {
        public int id_jornada { get; set; }
        public System.TimeSpan hr_entrada { get; set; }
        public System.TimeSpan hr_saida_almoco { get; set; }
        public System.TimeSpan hr_retor_almoco { get; set; }
        public System.TimeSpan hr_saida { get; set; }
        public string dia_semana { get; set; }
        public int id_jornada_trabalho { get; set; }
    
        public virtual tb_jornada_trabalho tb_jornada_trabalho { get; set; }
    }
}
