//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto_compra
    {
        public tb_produto_compra()
        {
            this.tb_estoque = new HashSet<tb_estoque>();
        }
    
        public int id_produto_compra { get; set; }
        public string nm_produto { get; set; }
        public int vl_preco { get; set; }
        public int qtd_produto { get; set; }
        public bool ds_entregue { get; set; }
        public Nullable<System.DateTime> dt_entrega { get; set; }
        public int id_fornecedor { get; set; }
        public System.DateTime dt_compra { get; set; }
    
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        public virtual tb_fornecedor tb_fornecedor { get; set; }
    }
}
