
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cultura_Musical.Database.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tb_produto
{

    public tb_produto()
    {

        this.tb_compra_item = new HashSet<tb_compra_item>();

        this.tb_estoque = new HashSet<tb_estoque>();

        this.tb_venda = new HashSet<tb_venda>();

    }


    public int id_produto { get; set; }

    public string nm_produto { get; set; }

    public int vl_preco { get; set; }

    public int qtd_produto { get; set; }



    public virtual ICollection<tb_compra_item> tb_compra_item { get; set; }

    public virtual ICollection<tb_estoque> tb_estoque { get; set; }

    public virtual ICollection<tb_venda> tb_venda { get; set; }

}

}
