//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_plano
    {
        public tb_plano()
        {
            this.tb_venda_plano = new HashSet<tb_venda_plano>();
        }
    
        public int id_plano { get; set; }
        public string nm_plano { get; set; }
        public string duracao { get; set; }
        public decimal preco { get; set; }
    
        public virtual ICollection<tb_venda_plano> tb_venda_plano { get; set; }
    }
}
