//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_plano
    {
        public tb_plano()
        {
            this.tb_venda_plano = new HashSet<tb_venda_plano>();
        }
    
        public int id_plano { get; set; }
        public string nm_plano { get; set; }
        public string duracao { get; set; }
        public decimal preco { get; set; }
        public string ds_descricao { get; set; }
        public int qtd_aula_semana { get; set; }
    
        public virtual ICollection<tb_venda_plano> tb_venda_plano { get; set; }
    }
}
