//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sala
    {
        public tb_sala()
        {
            this.tb_cliente_aula = new HashSet<tb_cliente_aula>();
        }
    
        public int id_sala { get; set; }
        public int nr_sala { get; set; }
        public int qtd_max_alunos { get; set; }
        public string tp_instrumento { get; set; }
    
        public virtual ICollection<tb_cliente_aula> tb_cliente_aula { get; set; }
    }
}
