//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cultura_Musical.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venda_plano
    {
        public int id_venda_plano { get; set; }
        public int id_plano { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime inicio { get; set; }
        public System.DateTime fim { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_plano tb_plano { get; set; }
    }
}
